#!/bin/bash
set -e 
set -o pipefail 

#   A simple script to hold common variables for ANGSD-wrapper

#   Define a list of samples
SAMPLE_LIST=/home/caryn89/angsd-wrapper/Example_Data/Maize/Maize_Samples.txt

#   Define a list of inbreeding coefficients
#	This should end in '_.indF'
SAMPLE_INBREEDING=/home/caryn89/angsd-wrapper/Example_Data/Maize/Maize_Inbreeding.indF

#   Ancestral sequence
ANC_SEQ=/home/caryn89/angsd-wrapper/Example_Data/Sequences/Tripsacum_TDD39103.fa

#   Reference sequence
REF_SEQ=/home/caryn89/angsd-wrapper/Example_Data/Sequences/Zea_mays.AGPv3.30.dna_sm.chromosome.10.fa

#   Name the project
PROJECT=Maize_Example

#   Where do we put the outfiles?
    #   Note, the final outdirectory will be
    #   ${SCRATCH}/${PROJECT}/<name_of_program/>
SCRATCH=/home/caryn89/angsd-wrapper/Example_Data/scratch

#   Define the region being looked at
#       Optional, but ANGSD is expensive to run without specifying regions to look at
REGIONS=/home/caryn89/angsd-wrapper/Example_Data/Maize/Maize_Regions.txt

#   Set common parameters for all methods
UNIQUE_ONLY=0
MIN_BASEQUAL=20
BAQ=1
MIN_IND=1
GT_LIKELIHOOD=2
MIN_MAPQ=30
N_CORES=32
DO_MAJORMINOR=1
DO_GENO=32
DO_MAF=1
DO_POST=1

